// Generated timezone options aligned with @vvo/tzdb used in web client.
class TimezoneOption {
  const TimezoneOption({
    required this.value,
    required this.label,
    required this.searchText,
    required this.offsetMinutes,
  });

  final String value;
  final String label;
  final String searchText;
  final int offsetMinutes;
}

const List<TimezoneOption> kTimezoneOptions = <TimezoneOption>[
  TimezoneOption(
    value: 'Pacific/Midway',
    label: 'UTC-11:00 American Samoa Time - Midway',
    searchText: 'Pacific/Midway Pacific/Midway American Samoa Time United States Minor Outlying Islands UM Midway',
    offsetMinutes: -660,
  ),
  TimezoneOption(
    value: 'Pacific/Pago_Pago',
    label: 'UTC-11:00 American Samoa Time - Pago Pago',
    searchText: 'Pacific/Pago_Pago Pacific/Pago_Pago US/Samoa Pacific/Samoa Pacific/Midway American Samoa Time American Samoa AS Pago Pago',
    offsetMinutes: -660,
  ),
  TimezoneOption(
    value: 'Pacific/Niue',
    label: 'UTC-11:00 Niue Time - Alofi',
    searchText: 'Pacific/Niue Pacific/Niue Niue Time Niue NU Alofi',
    offsetMinutes: -660,
  ),
  TimezoneOption(
    value: 'Pacific/Rarotonga',
    label: 'UTC-10:00 Cook Islands Time - Avarua',
    searchText: 'Pacific/Rarotonga Pacific/Rarotonga Cook Islands Time Cook Islands CK Avarua',
    offsetMinutes: -600,
  ),
  TimezoneOption(
    value: 'Pacific/Honolulu',
    label: 'UTC-10:00 Hawaii-Aleutian Time - Honolulu, East Honolulu',
    searchText: 'Pacific/Honolulu Pacific/Honolulu US/Hawaii Pacific/Johnston HST Hawaii-Aleutian Time United States US Honolulu East Honolulu Pearl City Makakilo / Kapolei / Honokai Hale',
    offsetMinutes: -600,
  ),
  TimezoneOption(
    value: 'Pacific/Tahiti',
    label: 'UTC-10:00 Tahiti Time - Faaa, Papeete',
    searchText: 'Pacific/Tahiti Pacific/Tahiti Tahiti Time French Polynesia PF Faaa Papeete Punaauia',
    offsetMinutes: -600,
  ),
  TimezoneOption(
    value: 'Pacific/Marquesas',
    label: 'UTC-09:30 Marquesas Time - Marquesas',
    searchText: 'Pacific/Marquesas Pacific/Marquesas Marquesas Time French Polynesia PF Marquesas',
    offsetMinutes: -570,
  ),
  TimezoneOption(
    value: 'Pacific/Gambier',
    label: 'UTC-09:00 Gambier Time - Gambier',
    searchText: 'Pacific/Gambier Pacific/Gambier Gambier Time French Polynesia PF Gambier',
    offsetMinutes: -540,
  ),
  TimezoneOption(
    value: 'America/Adak',
    label: 'UTC-09:00 Hawaii-Aleutian Time - Adak',
    searchText: 'America/Adak America/Adak US/Aleutian America/Atka Hawaii-Aleutian Time United States US Adak',
    offsetMinutes: -540,
  ),
  TimezoneOption(
    value: 'America/Anchorage',
    label: 'UTC-08:00 Alaska Time - Anchorage, Fairbanks',
    searchText: 'America/Anchorage America/Anchorage America/Juneau America/Metlakatla America/Nome America/Sitka America/Yakutat US/Alaska Alaska Time United States US Anchorage Fairbanks Juneau Eagle River',
    offsetMinutes: -480,
  ),
  TimezoneOption(
    value: 'Pacific/Pitcairn',
    label: 'UTC-08:00 Pitcairn Time - Adamstown',
    searchText: 'Pacific/Pitcairn Pacific/Pitcairn Pitcairn Time Pitcairn PN Adamstown',
    offsetMinutes: -480,
  ),
  TimezoneOption(
    value: 'America/Hermosillo',
    label: 'UTC-07:00 Mexican Pacific Time - Hermosillo, Culiacán',
    searchText: 'America/Hermosillo America/Hermosillo America/Mazatlan Mexico/BajaSur Mexican Pacific Time Mexico MX Hermosillo Culiacán Mazatlán Tepic',
    offsetMinutes: -420,
  ),
  TimezoneOption(
    value: 'America/Phoenix',
    label: 'UTC-07:00 Mountain Time - Phoenix, Tucson',
    searchText: 'America/Phoenix America/Phoenix MST US/Arizona America/Creston Mountain Time United States US Phoenix Tucson Mesa Chandler',
    offsetMinutes: -420,
  ),
  TimezoneOption(
    value: 'America/Los_Angeles',
    label: 'UTC-07:00 Pacific Time - Los Angeles, San Diego',
    searchText: 'America/Los_Angeles America/Los_Angeles US/Pacific PST8PDT Pacific Time United States US Los Angeles San Diego San Jose San Francisco',
    offsetMinutes: -420,
  ),
  TimezoneOption(
    value: 'America/Tijuana',
    label: 'UTC-07:00 Pacific Time - Tijuana, Mexicali',
    searchText: 'America/Tijuana America/Tijuana Mexico/BajaNorte America/Ensenada America/Santa_Isabel Pacific Time Mexico MX Tijuana Mexicali Ensenada Rosarito',
    offsetMinutes: -420,
  ),
  TimezoneOption(
    value: 'America/Vancouver',
    label: 'UTC-07:00 Pacific Time - Vancouver, Surrey',
    searchText: 'America/Vancouver America/Vancouver Canada/Pacific Pacific Time Canada CA Vancouver Surrey Victoria Burnaby',
    offsetMinutes: -420,
  ),
  TimezoneOption(
    value: 'America/Whitehorse',
    label: 'UTC-07:00 Yukon Time - Whitehorse, Fort St. John',
    searchText: 'America/Whitehorse America/Creston America/Dawson America/Dawson_Creek America/Fort_Nelson America/Whitehorse Canada/Yukon Yukon Time Canada CA Whitehorse Fort St. John Creston Dawson',
    offsetMinutes: -420,
  ),
  TimezoneOption(
    value: 'America/Belize',
    label: 'UTC-06:00 Central Time - Belize City, San Pedro',
    searchText: 'America/Belize America/Belize Central Time Belize BZ Belize City San Pedro Orange Walk Belmopan',
    offsetMinutes: -360,
  ),
  TimezoneOption(
    value: 'America/Guatemala',
    label: 'UTC-06:00 Central Time - Guatemala City, Villa Nueva',
    searchText: 'America/Guatemala America/Guatemala Central Time Guatemala GT Guatemala City Villa Nueva Mixco Cobán',
    offsetMinutes: -360,
  ),
  TimezoneOption(
    value: 'America/Managua',
    label: 'UTC-06:00 Central Time - Managua, León',
    searchText: 'America/Managua America/Managua Central Time Nicaragua NI Managua León Masaya Chinandega',
    offsetMinutes: -360,
  ),
  TimezoneOption(
    value: 'America/Mexico_City',
    label: 'UTC-06:00 Central Time - Mexico City, Iztapalapa',
    searchText: 'America/Mexico_City America/Bahia_Banderas America/Chihuahua America/Merida America/Mexico_City America/Monterrey Mexico/General Central Time Mexico MX Mexico City Iztapalapa Puebla Ecatepec de Morelos',
    offsetMinutes: -360,
  ),
  TimezoneOption(
    value: 'America/Costa_Rica',
    label: 'UTC-06:00 Central Time - San José, Limón',
    searchText: 'America/Costa_Rica America/Costa_Rica Central Time Costa Rica CR San José Limón San Francisco Alajuela',
    offsetMinutes: -360,
  ),
  TimezoneOption(
    value: 'America/El_Salvador',
    label: 'UTC-06:00 Central Time - San Salvador, Soyapango',
    searchText: 'America/El_Salvador America/El_Salvador Central Time El Salvador SV San Salvador Soyapango San Miguel Santa Ana',
    offsetMinutes: -360,
  ),
  TimezoneOption(
    value: 'America/Regina',
    label: 'UTC-06:00 Central Time - Saskatoon, Regina',
    searchText: 'America/Regina America/Regina America/Swift_Current Canada/Saskatchewan Central Time Canada CA Saskatoon Regina Prince Albert Moose Jaw',
    offsetMinutes: -360,
  ),
  TimezoneOption(
    value: 'America/Tegucigalpa',
    label: 'UTC-06:00 Central Time - Tegucigalpa, San Pedro Sula',
    searchText: 'America/Tegucigalpa America/Tegucigalpa Central Time Honduras HN Tegucigalpa San Pedro Sula La Ceiba Choloma',
    offsetMinutes: -360,
  ),
  TimezoneOption(
    value: 'Pacific/Galapagos',
    label: 'UTC-06:00 Galapagos Time - Galapagos',
    searchText: 'Pacific/Galapagos Pacific/Galapagos Galapagos Time Ecuador EC Galapagos',
    offsetMinutes: -360,
  ),
  TimezoneOption(
    value: 'America/Edmonton',
    label: 'UTC-06:00 Mountain Time - Calgary, Edmonton',
    searchText: 'America/Edmonton America/Cambridge_Bay America/Edmonton America/Inuvik Canada/Mountain America/Yellowknife Mountain Time Canada CA Calgary Edmonton Lethbridge Red Deer',
    offsetMinutes: -360,
  ),
  TimezoneOption(
    value: 'America/Ciudad_Juarez',
    label: 'UTC-06:00 Mountain Time - Ciudad Juárez',
    searchText: 'America/Ciudad_Juarez America/Ciudad_Juarez Mountain Time Mexico MX Ciudad Juárez',
    offsetMinutes: -360,
  ),
  TimezoneOption(
    value: 'America/Denver',
    label: 'UTC-06:00 Mountain Time - Denver, El Paso',
    searchText: 'America/Denver America/Boise America/Denver MST7MDT Navajo US/Mountain America/Shiprock Mountain Time United States US Denver El Paso Albuquerque Colorado Springs',
    offsetMinutes: -360,
  ),
  TimezoneOption(
    value: 'America/Rio_Branco',
    label: 'UTC-05:00 Acre Time - Rio Branco, Cruzeiro do Sul',
    searchText: 'America/Rio_Branco America/Eirunepe America/Rio_Branco Brazil/Acre America/Porto_Acre Acre Time Brazil BR Rio Branco Cruzeiro do Sul Tarauacá Sena Madureira',
    offsetMinutes: -300,
  ),
  TimezoneOption(
    value: 'America/Chicago',
    label: 'UTC-05:00 Central Time - Chicago, Houston',
    searchText: 'America/Chicago America/Chicago America/Indiana/Knox America/Indiana/Tell_City America/Menominee America/North_Dakota/Beulah America/North_Dakota/Center America/North_Dakota/New_Salem CST6CDT US/Central US/Indiana-Starke America/Knox_IN Central Time United States US Chicago Houston San Antonio Dallas',
    offsetMinutes: -300,
  ),
  TimezoneOption(
    value: 'America/Matamoros',
    label: 'UTC-05:00 Central Time - Reynosa, Heroica Matamoros',
    searchText: 'America/Matamoros America/Matamoros America/Ojinaga Central Time Mexico MX Reynosa Heroica Matamoros Nuevo Laredo Ciudad Acuña',
    offsetMinutes: -300,
  ),
  TimezoneOption(
    value: 'America/Winnipeg',
    label: 'UTC-05:00 Central Time - Winnipeg, Brandon',
    searchText: 'America/Winnipeg America/Rankin_Inlet America/Resolute America/Winnipeg Canada/Central America/Rainy_River Central Time Canada CA Winnipeg Brandon Steinbach Kenora',
    offsetMinutes: -300,
  ),
  TimezoneOption(
    value: 'America/Bogota',
    label: 'UTC-05:00 Colombia Time - Bogotá, Cali',
    searchText: 'America/Bogota America/Bogota Colombia Time Colombia CO Bogotá Cali Medellín Barranquilla',
    offsetMinutes: -300,
  ),
  TimezoneOption(
    value: 'Pacific/Easter',
    label: 'UTC-05:00 Easter Island Time - Easter',
    searchText: 'Pacific/Easter Pacific/Easter Chile/EasterIsland Easter Island Time Chile CL Easter',
    offsetMinutes: -300,
  ),
  TimezoneOption(
    value: 'America/Atikokan',
    label: 'UTC-05:00 Eastern Time - Atikokan',
    searchText: 'America/Atikokan America/Atikokan Eastern Time Canada CA Atikokan',
    offsetMinutes: -300,
  ),
  TimezoneOption(
    value: 'America/Cancun',
    label: 'UTC-05:00 Eastern Time - Cancún, Chetumal',
    searchText: 'America/Cancun America/Cancun Eastern Time Mexico MX Cancún Chetumal Playa del Carmen Cozumel',
    offsetMinutes: -300,
  ),
  TimezoneOption(
    value: 'America/Cayman',
    label: 'UTC-05:00 Eastern Time - George Town, West Bay',
    searchText: 'America/Cayman America/Cayman Eastern Time Cayman Islands KY George Town West Bay',
    offsetMinutes: -300,
  ),
  TimezoneOption(
    value: 'America/Jamaica',
    label: 'UTC-05:00 Eastern Time - Kingston, New Kingston',
    searchText: 'America/Jamaica America/Jamaica Jamaica Eastern Time Jamaica JM Kingston New Kingston Spanish Town Portmore',
    offsetMinutes: -300,
  ),
  TimezoneOption(
    value: 'America/Panama',
    label: 'UTC-05:00 Eastern Time - Panamá, San Miguelito',
    searchText: 'America/Panama America/Panama EST America/Atikokan America/Cayman America/Coral_Harbour Eastern Time Panama PA Panamá San Miguelito Juan Díaz David',
    offsetMinutes: -300,
  ),
  TimezoneOption(
    value: 'America/Guayaquil',
    label: 'UTC-05:00 Ecuador Time - Quito, Guayaquil',
    searchText: 'America/Guayaquil America/Guayaquil Ecuador Time Ecuador EC Quito Guayaquil Cuenca Santo Domingo de los Colorados',
    offsetMinutes: -300,
  ),
  TimezoneOption(
    value: 'America/Lima',
    label: 'UTC-05:00 Peru Time - Lima, Callao',
    searchText: 'America/Lima America/Lima Peru Time Peru PE Lima Callao Arequipa Trujillo',
    offsetMinutes: -300,
  ),
  TimezoneOption(
    value: 'America/Manaus',
    label: 'UTC-04:00 Amazon Time - Manaus, Campo Grande',
    searchText: 'America/Manaus America/Boa_Vista America/Campo_Grande America/Cuiaba America/Manaus America/Porto_Velho Brazil/West Amazon Time Brazil BR Manaus Campo Grande Cuiabá Porto Velho',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/St_Kitts',
    label: 'UTC-04:00 Atlantic Time - Basseterre',
    searchText: 'America/St_Kitts America/St_Kitts Atlantic Time Saint Kitts and Nevis KN Basseterre',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/Blanc-Sablon',
    label: 'UTC-04:00 Atlantic Time - Blanc-Sablon',
    searchText: 'America/Blanc-Sablon America/Blanc-Sablon Atlantic Time Canada CA Blanc-Sablon',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/Montserrat',
    label: 'UTC-04:00 Atlantic Time - Brades, Plymouth',
    searchText: 'America/Montserrat America/Montserrat Atlantic Time Montserrat MS Brades Plymouth',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/Barbados',
    label: 'UTC-04:00 Atlantic Time - Bridgetown',
    searchText: 'America/Barbados America/Barbados Atlantic Time Barbados BB Bridgetown',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/Port_of_Spain',
    label: 'UTC-04:00 Atlantic Time - Chaguanas, Mon Repos',
    searchText: 'America/Port_of_Spain America/Port_of_Spain Atlantic Time Trinidad and Tobago TT Chaguanas Mon Repos San Fernando Port of Spain',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/Martinique',
    label: 'UTC-04:00 Atlantic Time - Fort-de-France, Le Lamentin',
    searchText: 'America/Martinique America/Martinique Atlantic Time Martinique MQ Fort-de-France Le Lamentin Le Robert Sainte-Marie',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/St_Lucia',
    label: 'UTC-04:00 Atlantic Time - Gros Islet, Castries',
    searchText: 'America/St_Lucia America/St_Lucia Atlantic Time Saint Lucia LC Gros Islet Castries',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/St_Barthelemy',
    label: 'UTC-04:00 Atlantic Time - Gustavia',
    searchText: 'America/St_Barthelemy America/St_Barthelemy Atlantic Time Saint Barthelemy BL Gustavia',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/St_Vincent',
    label: 'UTC-04:00 Atlantic Time - Kingstown, Calliaqua',
    searchText: 'America/St_Vincent America/St_Vincent Atlantic Time Saint Vincent and the Grenadines VC Kingstown Calliaqua',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/Kralendijk',
    label: 'UTC-04:00 Atlantic Time - Kralendijk',
    searchText: 'America/Kralendijk America/Kralendijk Atlantic Time Bonaire, Saint Eustatius and Saba  BQ Kralendijk',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/Guadeloupe',
    label: 'UTC-04:00 Atlantic Time - Les Abymes, Baie-Mahault',
    searchText: 'America/Guadeloupe America/Guadeloupe Atlantic Time Guadeloupe GP Les Abymes Baie-Mahault Le Gosier Petit-Bourg',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/Marigot',
    label: 'UTC-04:00 Atlantic Time - Marigot',
    searchText: 'America/Marigot America/Marigot Atlantic Time Saint Martin MF Marigot',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/Aruba',
    label: 'UTC-04:00 Atlantic Time - Oranjestad, Noord',
    searchText: 'America/Aruba America/Aruba Atlantic Time Aruba AW Oranjestad Noord Tanki Leendert San Nicolas',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/Lower_Princes',
    label: 'UTC-04:00 Atlantic Time - Philipsburg',
    searchText: 'America/Lower_Princes America/Lower_Princes Atlantic Time Sint Maarten SX Philipsburg',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/Tortola',
    label: 'UTC-04:00 Atlantic Time - Road Town',
    searchText: 'America/Tortola America/Tortola Atlantic Time British Virgin Islands VG Road Town',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/Dominica',
    label: 'UTC-04:00 Atlantic Time - Roseau',
    searchText: 'America/Dominica America/Dominica Atlantic Time Dominica DM Roseau',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/St_Thomas',
    label: 'UTC-04:00 Atlantic Time - Saint Croix, Charlotte Amalie',
    searchText: 'America/St_Thomas America/St_Thomas Atlantic Time U.S. Virgin Islands VI Saint Croix Charlotte Amalie',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/Grenada',
    label: "UTC-04:00 Atlantic Time - Saint George's",
    searchText: "America/Grenada America/Grenada Atlantic Time Grenada GD Saint George's",
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/Antigua',
    label: 'UTC-04:00 Atlantic Time - Saint John’s',
    searchText: 'America/Antigua America/Antigua Atlantic Time Antigua and Barbuda AG Saint John’s',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/Puerto_Rico',
    label: 'UTC-04:00 Atlantic Time - San Juan, Bayamón',
    searchText: 'America/Puerto_Rico America/Puerto_Rico America/Virgin America/Anguilla America/Antigua America/Aruba America/Blanc-Sablon America/Curacao America/Dominica America/Grenada America/Guadeloupe America/Kralendijk America/Lower_Princes America/Marigot America/Montserrat America/Port_of_Spain America/St_Barthelemy America/St_Kitts America/St_Lucia America/St_Thomas America/St_Vincent America/Tortola Atlantic Time Puerto Rico PR San Juan Bayamón Carolina Ponce',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/Santo_Domingo',
    label: 'UTC-04:00 Atlantic Time - Santo Domingo, Santiago de los Caballeros',
    searchText: 'America/Santo_Domingo America/Santo_Domingo Atlantic Time Dominican Republic DO Santo Domingo Santiago de los Caballeros Santo Domingo Oeste Santo Domingo Este',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/Anguilla',
    label: 'UTC-04:00 Atlantic Time - The Valley',
    searchText: 'America/Anguilla America/Anguilla Atlantic Time Anguilla AI The Valley',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/Curacao',
    label: 'UTC-04:00 Atlantic Time - Willemstad, Bandariba',
    searchText: 'America/Curacao America/Curacao Atlantic Time Curacao CW Willemstad Bandariba',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/La_Paz',
    label: 'UTC-04:00 Bolivia Time - La Paz, Santa Cruz de la Sierra',
    searchText: 'America/La_Paz America/La_Paz Bolivia Time Bolivia BO La Paz Santa Cruz de la Sierra Cochabamba Sucre',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/Havana',
    label: 'UTC-04:00 Cuba Time - Havana, Santiago de Cuba',
    searchText: 'America/Havana America/Havana Cuba Cuba Time Cuba CU Havana Santiago de Cuba Camagüey Holguín',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/Nassau',
    label: 'UTC-04:00 Eastern Time - Nassau, Lucaya',
    searchText: 'America/Nassau America/Nassau Eastern Time Bahamas BS Nassau Lucaya Freeport Killarney',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/New_York',
    label: 'UTC-04:00 Eastern Time - New York City, Brooklyn',
    searchText: 'America/New_York America/Detroit America/Indiana/Indianapolis America/Indiana/Marengo America/Indiana/Petersburg America/Indiana/Vevay America/Indiana/Vincennes America/Indiana/Winamac America/Kentucky/Louisville America/Kentucky/Monticello America/New_York US/Michigan US/East-Indiana America/Indianapolis America/Fort_Wayne America/Louisville EST5EDT US/Eastern Eastern Time United States US New York City Brooklyn Queens Philadelphia',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/Port-au-Prince',
    label: 'UTC-04:00 Eastern Time - Port-au-Prince, Carrefour',
    searchText: 'America/Port-au-Prince America/Port-au-Prince Eastern Time Haiti HT Port-au-Prince Carrefour Delmas Port-de-Paix',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/Grand_Turk',
    label: 'UTC-04:00 Eastern Time - Providenciales, Cockburn Town',
    searchText: 'America/Grand_Turk America/Grand_Turk Eastern Time Turks and Caicos Islands TC Providenciales Cockburn Town',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/Toronto',
    label: 'UTC-04:00 Eastern Time - Toronto, Montréal',
    searchText: 'America/Toronto America/Iqaluit America/Toronto America/Pangnirtung Canada/Eastern America/Nassau America/Montreal America/Nipigon America/Thunder_Bay Eastern Time Canada CA Toronto Montréal Ottawa Mississauga',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/Guyana',
    label: 'UTC-04:00 Guyana Time - Georgetown, Linden',
    searchText: 'America/Guyana America/Guyana Guyana Time Guyana GY Georgetown Linden New Amsterdam',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/Caracas',
    label: 'UTC-04:00 Venezuela Time - Caracas, Maracaibo',
    searchText: 'America/Caracas America/Caracas Venezuela Time Venezuela VE Caracas Maracaibo Valencia Barquisimeto',
    offsetMinutes: -240,
  ),
  TimezoneOption(
    value: 'America/Argentina/Buenos_Aires',
    label: 'UTC-03:00 Argentina Time - Buenos Aires, Córdoba',
    searchText: 'America/Argentina/Buenos_Aires America/Argentina/Buenos_Aires America/Argentina/Catamarca America/Argentina/Cordoba America/Argentina/Jujuy America/Argentina/La_Rioja America/Argentina/Mendoza America/Argentina/Rio_Gallegos America/Argentina/Salta America/Argentina/San_Juan America/Argentina/San_Luis America/Argentina/Tucuman America/Argentina/Ushuaia America/Buenos_Aires America/Catamarca America/Argentina/ComodRivadavia America/Cordoba America/Rosario America/Jujuy America/Mendoza Argentina Time Argentina AR Buenos Aires Córdoba Rosario Mar del Plata',
    offsetMinutes: -180,
  ),
  TimezoneOption(
    value: 'America/Halifax',
    label: 'UTC-03:00 Atlantic Time - Halifax, Sydney',
    searchText: 'America/Halifax America/Glace_Bay America/Goose_Bay America/Halifax America/Moncton Canada/Atlantic Atlantic Time Canada CA Halifax Sydney Dartmouth Moncton',
    offsetMinutes: -180,
  ),
  TimezoneOption(
    value: 'Atlantic/Bermuda',
    label: 'UTC-03:00 Atlantic Time - Hamilton',
    searchText: 'Atlantic/Bermuda Atlantic/Bermuda Atlantic Time Bermuda BM Hamilton',
    offsetMinutes: -180,
  ),
  TimezoneOption(
    value: 'America/Thule',
    label: 'UTC-03:00 Atlantic Time - Thule',
    searchText: 'America/Thule America/Thule Atlantic Time Greenland GL Thule',
    offsetMinutes: -180,
  ),
  TimezoneOption(
    value: 'America/Sao_Paulo',
    label: 'UTC-03:00 Brasilia Time - São Paulo, Rio de Janeiro',
    searchText: 'America/Sao_Paulo America/Araguaina America/Bahia America/Belem America/Fortaleza America/Maceio America/Recife America/Santarem America/Sao_Paulo Brazil/East Brasilia Time Brazil BR São Paulo Rio de Janeiro Belo Horizonte Salvador',
    offsetMinutes: -180,
  ),
  TimezoneOption(
    value: 'Antarctica/Palmer',
    label: 'UTC-03:00 Chile Time - Palmer, Rothera',
    searchText: 'Antarctica/Palmer Antarctica/Palmer Antarctica/Rothera Chile Time Antarctica AQ Palmer Rothera',
    offsetMinutes: -180,
  ),
  TimezoneOption(
    value: 'America/Punta_Arenas',
    label: 'UTC-03:00 Chile Time - Punta Arenas, Coyhaique',
    searchText: 'America/Punta_Arenas America/Coyhaique America/Punta_Arenas Chile Time Chile CL Punta Arenas Coyhaique Puerto Natales Puerto Aysén',
    offsetMinutes: -180,
  ),
  TimezoneOption(
    value: 'America/Santiago',
    label: 'UTC-03:00 Chile Time - Santiago, Puente Alto',
    searchText: 'America/Santiago America/Santiago Chile/Continental Chile Time Chile CL Santiago Puente Alto Maipú Antofagasta',
    offsetMinutes: -180,
  ),
  TimezoneOption(
    value: 'Atlantic/Stanley',
    label: 'UTC-03:00 Falkland Islands Time - Stanley',
    searchText: 'Atlantic/Stanley Atlantic/Stanley Falkland Islands Time Falkland Islands FK Stanley',
    offsetMinutes: -180,
  ),
  TimezoneOption(
    value: 'America/Cayenne',
    label: 'UTC-03:00 French Guiana Time - Cayenne, Matoury',
    searchText: 'America/Cayenne America/Cayenne French Guiana Time French Guiana GF Cayenne Matoury Saint-Laurent-du-Maroni Kourou',
    offsetMinutes: -180,
  ),
  TimezoneOption(
    value: 'America/Asuncion',
    label: 'UTC-03:00 Paraguay Time - Asunción, Ciudad del Este',
    searchText: 'America/Asuncion America/Asuncion Paraguay Time Paraguay PY Asunción Ciudad del Este San Lorenzo Capiatá',
    offsetMinutes: -180,
  ),
  TimezoneOption(
    value: 'America/Paramaribo',
    label: 'UTC-03:00 Suriname Time - Paramaribo, Blauwgrond',
    searchText: 'America/Paramaribo America/Paramaribo Suriname Time Suriname SR Paramaribo Blauwgrond Rainville Flora',
    offsetMinutes: -180,
  ),
  TimezoneOption(
    value: 'America/Montevideo',
    label: 'UTC-03:00 Uruguay Time - Montevideo, Salto',
    searchText: 'America/Montevideo America/Montevideo Uruguay Time Uruguay UY Montevideo Salto Paysandú Las Piedras',
    offsetMinutes: -180,
  ),
  TimezoneOption(
    value: 'America/St_Johns',
    label: "UTC-02:30 Newfoundland Time - St. John's, Mount Pearl",
    searchText: "America/St_Johns America/St_Johns Canada/Newfoundland Newfoundland Time Canada CA St. John's Mount Pearl Paradise Corner Brook",
    offsetMinutes: -150,
  ),
  TimezoneOption(
    value: 'America/Noronha',
    label: 'UTC-02:00 Fernando de Noronha Time - Noronha',
    searchText: 'America/Noronha America/Noronha Brazil/DeNoronha Fernando de Noronha Time Brazil BR Noronha',
    offsetMinutes: -120,
  ),
  TimezoneOption(
    value: 'Atlantic/South_Georgia',
    label: 'UTC-02:00 South Georgia Time - Grytviken',
    searchText: 'Atlantic/South_Georgia Atlantic/South_Georgia South Georgia Time South Georgia and the South Sandwich Islands GS Grytviken',
    offsetMinutes: -120,
  ),
  TimezoneOption(
    value: 'America/Miquelon',
    label: 'UTC-02:00 St. Pierre & Miquelon Time - Saint-Pierre',
    searchText: 'America/Miquelon America/Miquelon St. Pierre & Miquelon Time Saint Pierre and Miquelon PM Saint-Pierre',
    offsetMinutes: -120,
  ),
  TimezoneOption(
    value: 'Atlantic/Cape_Verde',
    label: 'UTC-01:00 Cape Verde Time - Praia, Mindelo',
    searchText: 'Atlantic/Cape_Verde Atlantic/Cape_Verde Cape Verde Time Cabo Verde CV Praia Mindelo Espargos Assomada',
    offsetMinutes: -60,
  ),
  TimezoneOption(
    value: 'America/Nuuk',
    label: 'UTC-01:00 Greenland Time - Nuuk, Scoresbysund',
    searchText: 'America/Nuuk America/Nuuk America/Scoresbysund America/Godthab Greenland Time Greenland GL Nuuk Scoresbysund',
    offsetMinutes: -60,
  ),
  TimezoneOption(
    value: 'Atlantic/Azores',
    label: 'UTC+00:00 Azores Time - Ponta Delgada',
    searchText: 'Atlantic/Azores Atlantic/Azores Azores Time Portugal PT Ponta Delgada',
    offsetMinutes: 0,
  ),
  TimezoneOption(
    value: 'Africa/Abidjan',
    label: 'UTC+00:00 Greenwich Mean Time - Abidjan, Abobo',
    searchText: 'Africa/Abidjan Africa/Abidjan Iceland Africa/Accra Africa/Bamako Africa/Banjul Africa/Conakry Africa/Dakar Africa/Freetown Africa/Lome Africa/Nouakchott Africa/Ouagadougou Atlantic/Reykjavik Atlantic/St_Helena Africa/Timbuktu Greenwich Mean Time Ivory Coast CI Abidjan Abobo Bouaké Korhogo',
    offsetMinutes: 0,
  ),
  TimezoneOption(
    value: 'Africa/Bamako',
    label: 'UTC+00:00 Greenwich Mean Time - Bamako, Sikasso',
    searchText: 'Africa/Bamako Africa/Bamako Greenwich Mean Time Mali ML Bamako Sikasso Koutiala Ségou',
    offsetMinutes: 0,
  ),
  TimezoneOption(
    value: 'Africa/Bissau',
    label: 'UTC+00:00 Greenwich Mean Time - Bissau, Gabú',
    searchText: 'Africa/Bissau Africa/Bissau Greenwich Mean Time Guinea-Bissau GW Bissau Gabú Bafatá Xitole',
    offsetMinutes: 0,
  ),
  TimezoneOption(
    value: 'Africa/Conakry',
    label: 'UTC+00:00 Greenwich Mean Time - Conakry, Camayenne',
    searchText: 'Africa/Conakry Africa/Conakry Greenwich Mean Time Guinea GN Conakry Camayenne Nzérékoré Kankan',
    offsetMinutes: 0,
  ),
  TimezoneOption(
    value: 'Africa/Dakar',
    label: 'UTC+00:00 Greenwich Mean Time - Dakar, Touba',
    searchText: 'Africa/Dakar Africa/Dakar Greenwich Mean Time Senegal SN Dakar Touba Pikine Guédiawaye',
    offsetMinutes: 0,
  ),
  TimezoneOption(
    value: 'America/Danmarkshavn',
    label: 'UTC+00:00 Greenwich Mean Time - Danmarkshavn',
    searchText: 'America/Danmarkshavn America/Danmarkshavn Greenwich Mean Time Greenland GL Danmarkshavn',
    offsetMinutes: 0,
  ),
  TimezoneOption(
    value: 'Africa/Freetown',
    label: 'UTC+00:00 Greenwich Mean Time - Freetown, Bo',
    searchText: 'Africa/Freetown Africa/Freetown Greenwich Mean Time Sierra Leone SL Freetown Bo Kenema Koidu',
    offsetMinutes: 0,
  ),
  TimezoneOption(
    value: 'Atlantic/St_Helena',
    label: 'UTC+00:00 Greenwich Mean Time - Jamestown',
    searchText: 'Atlantic/St_Helena Atlantic/St_Helena Greenwich Mean Time Saint Helena SH Jamestown',
    offsetMinutes: 0,
  ),
  TimezoneOption(
    value: 'Africa/Accra',
    label: 'UTC+00:00 Greenwich Mean Time - Kumasi, Accra',
    searchText: 'Africa/Accra Africa/Accra Greenwich Mean Time Ghana GH Kumasi Accra Tamale Takoradi',
    offsetMinutes: 0,
  ),
  TimezoneOption(
    value: 'Africa/Lome',
    label: 'UTC+00:00 Greenwich Mean Time - Lomé, Sokodé',
    searchText: 'Africa/Lome Africa/Lome Greenwich Mean Time Togo TG Lomé Sokodé Kara Atakpamé',
    offsetMinutes: 0,
  ),
  TimezoneOption(
    value: 'Africa/Monrovia',
    label: 'UTC+00:00 Greenwich Mean Time - Monrovia, Gbarnga',
    searchText: 'Africa/Monrovia Africa/Monrovia Greenwich Mean Time Liberia LR Monrovia Gbarnga Buchanan Ganta',
    offsetMinutes: 0,
  ),
  TimezoneOption(
    value: 'Africa/Nouakchott',
    label: 'UTC+00:00 Greenwich Mean Time - Nouakchott, Nouadhibou',
    searchText: 'Africa/Nouakchott Africa/Nouakchott Greenwich Mean Time Mauritania MR Nouakchott Nouadhibou Kiffa Dar Naim',
    offsetMinutes: 0,
  ),
  TimezoneOption(
    value: 'Africa/Ouagadougou',
    label: 'UTC+00:00 Greenwich Mean Time - Ouagadougou, Bobo-Dioulasso',
    searchText: 'Africa/Ouagadougou Africa/Ouagadougou Greenwich Mean Time Burkina Faso BF Ouagadougou Bobo-Dioulasso Koudougou Saaba',
    offsetMinutes: 0,
  ),
  TimezoneOption(
    value: 'Atlantic/Reykjavik',
    label: 'UTC+00:00 Greenwich Mean Time - Reykjavík, Kópavogur',
    searchText: 'Atlantic/Reykjavik Atlantic/Reykjavik Greenwich Mean Time Iceland IS Reykjavík Kópavogur Hafnarfjörður Reykjanesbær',
    offsetMinutes: 0,
  ),
  TimezoneOption(
    value: 'Africa/Sao_Tome',
    label: 'UTC+00:00 Greenwich Mean Time - São Tomé',
    searchText: 'Africa/Sao_Tome Africa/Sao_Tome Greenwich Mean Time Sao Tome and Principe ST São Tomé',
    offsetMinutes: 0,
  ),
  TimezoneOption(
    value: 'Africa/Banjul',
    label: 'UTC+00:00 Greenwich Mean Time - Serekunda, Brikama',
    searchText: 'Africa/Banjul Africa/Banjul Greenwich Mean Time Gambia GM Serekunda Brikama Bununka Kunda Sukuta',
    offsetMinutes: 0,
  ),
  TimezoneOption(
    value: 'UTC',
    label: 'UTC+00:00 UTC',
    searchText: 'UTC Etc/UTC Etc/UCT UCT UTC Universal Zulu Coordinated Universal Time (UTC)',
    offsetMinutes: 0,
  ),
  TimezoneOption(
    value: 'Africa/Algiers',
    label: 'UTC+01:00 Central European Time - Algiers, Oran',
    searchText: 'Africa/Algiers Africa/Algiers Central European Time Algeria DZ Algiers Oran Constantine Annaba',
    offsetMinutes: 60,
  ),
  TimezoneOption(
    value: 'Africa/Tunis',
    label: 'UTC+01:00 Central European Time - Tunis, Sfax',
    searchText: 'Africa/Tunis Africa/Tunis Central European Time Tunisia TN Tunis Sfax Sousse Kairouan',
    offsetMinutes: 60,
  ),
  TimezoneOption(
    value: 'Europe/Isle_of_Man',
    label: 'UTC+01:00 Greenwich Mean Time - Douglas',
    searchText: 'Europe/Isle_of_Man Europe/Isle_of_Man Greenwich Mean Time Isle of Man IM Douglas',
    offsetMinutes: 60,
  ),
  TimezoneOption(
    value: 'Europe/Dublin',
    label: 'UTC+01:00 Greenwich Mean Time - Dublin, South Dublin',
    searchText: 'Europe/Dublin Europe/Dublin Eire Greenwich Mean Time Ireland IE Dublin South Dublin Cork Limerick',
    offsetMinutes: 60,
  ),
  TimezoneOption(
    value: 'Europe/London',
    label: 'UTC+01:00 Greenwich Mean Time - London, Birmingham',
    searchText: 'Europe/London Europe/London GB GB-Eire Europe/Guernsey Europe/Isle_of_Man Europe/Jersey Europe/Belfast Greenwich Mean Time United Kingdom GB London Birmingham Glasgow Manchester',
    offsetMinutes: 60,
  ),
  TimezoneOption(
    value: 'Europe/Jersey',
    label: 'UTC+01:00 Greenwich Mean Time - Saint Helier',
    searchText: 'Europe/Jersey Europe/Jersey Greenwich Mean Time Jersey JE Saint Helier',
    offsetMinutes: 60,
  ),
  TimezoneOption(
    value: 'Europe/Guernsey',
    label: 'UTC+01:00 Greenwich Mean Time - Saint Peter Port',
    searchText: 'Europe/Guernsey Europe/Guernsey Greenwich Mean Time Guernsey GG Saint Peter Port',
    offsetMinutes: 60,
  ),
  TimezoneOption(
    value: 'Africa/Bangui',
    label: 'UTC+01:00 West Africa Time - Bangui, Bimbo',
    searchText: 'Africa/Bangui Africa/Bangui West Africa Time Central African Republic CF Bangui Bimbo Bégoua Carnot',
    offsetMinutes: 60,
  ),
  TimezoneOption(
    value: 'Africa/Malabo',
    label: 'UTC+01:00 West Africa Time - Bata, Malabo',
    searchText: 'Africa/Malabo Africa/Malabo West Africa Time Equatorial Guinea GQ Bata Malabo Ebebiyin',
    offsetMinutes: 60,
  ),
  TimezoneOption(
    value: 'Africa/Brazzaville',
    label: 'UTC+01:00 West Africa Time - Brazzaville, Pointe-Noire',
    searchText: 'Africa/Brazzaville Africa/Brazzaville West Africa Time Republic of the Congo CG Brazzaville Pointe-Noire Dolisie Nkayi',
    offsetMinutes: 60,
  ),
  TimezoneOption(
    value: 'Africa/Porto-Novo',
    label: 'UTC+01:00 West Africa Time - Cotonou, Abomey-Calavi',
    searchText: 'Africa/Porto-Novo Africa/Porto-Novo West Africa Time Benin BJ Cotonou Abomey-Calavi Porto-Novo Parakou',
    offsetMinutes: 60,
  ),
  TimezoneOption(
    value: 'Africa/Douala',
    label: 'UTC+01:00 West Africa Time - Douala, Yaoundé',
    searchText: 'Africa/Douala Africa/Douala West Africa Time Cameroon CM Douala Yaoundé Bamenda Bafoussam',
    offsetMinutes: 60,
  ),
  TimezoneOption(
    value: 'Africa/Kinshasa',
    label: 'UTC+01:00 West Africa Time - Kinshasa, Kikwit',
    searchText: 'Africa/Kinshasa Africa/Kinshasa West Africa Time Democratic Republic of the Congo CD Kinshasa Kikwit Masina Mbandaka',
    offsetMinutes: 60,
  ),
  TimezoneOption(
    value: 'Africa/Lagos',
    label: 'UTC+01:00 West Africa Time - Lagos, Kano',
    searchText: 'Africa/Lagos Africa/Lagos Africa/Bangui Africa/Brazzaville Africa/Douala Africa/Kinshasa Africa/Libreville Africa/Luanda Africa/Malabo Africa/Niamey Africa/Porto-Novo West Africa Time Nigeria NG Lagos Kano Ibadan Abuja',
    offsetMinutes: 60,
  ),
  TimezoneOption(
    value: 'Africa/Libreville',
    label: 'UTC+01:00 West Africa Time - Libreville, Port-Gentil',
    searchText: 'Africa/Libreville Africa/Libreville West Africa Time Gabon GA Libreville Port-Gentil Franceville Owendo',
    offsetMinutes: 60,
  ),
  TimezoneOption(
    value: 'Africa/Luanda',
    label: 'UTC+01:00 West Africa Time - Luanda, Lubango',
    searchText: 'Africa/Luanda Africa/Luanda West Africa Time Angola AO Luanda Lubango Huambo Benguela',
    offsetMinutes: 60,
  ),
  TimezoneOption(
    value: 'Africa/Ndjamena',
    label: "UTC+01:00 West Africa Time - N'Djamena, Moundou",
    searchText: "Africa/Ndjamena Africa/Ndjamena West Africa Time Chad TD N'Djamena Moundou Abéché Sarh",
    offsetMinutes: 60,
  ),
  TimezoneOption(
    value: 'Africa/Niamey',
    label: 'UTC+01:00 West Africa Time - Niamey, Maradi',
    searchText: 'Africa/Niamey Africa/Niamey West Africa Time Niger NE Niamey Maradi Zinder Tahoua',
    offsetMinutes: 60,
  ),
  TimezoneOption(
    value: 'Africa/Casablanca',
    label: 'UTC+01:00 Western European Time - Casablanca, Rabat',
    searchText: 'Africa/Casablanca Africa/Casablanca Western European Time Morocco MA Casablanca Rabat Fes Tangier',
    offsetMinutes: 60,
  ),
  TimezoneOption(
    value: 'Africa/El_Aaiun',
    label: 'UTC+01:00 Western European Time - Laayoune, Dakhla',
    searchText: 'Africa/El_Aaiun Africa/El_Aaiun Western European Time Western Sahara EH Laayoune Dakhla Boujdour',
    offsetMinutes: 60,
  ),
  TimezoneOption(
    value: 'Atlantic/Canary',
    label: 'UTC+01:00 Western European Time - Las Palmas de Gran Canaria, Santa Cruz de Tenerife',
    searchText: 'Atlantic/Canary Atlantic/Canary Western European Time Spain ES Las Palmas de Gran Canaria Santa Cruz de Tenerife La Laguna Telde',
    offsetMinutes: 60,
  ),
  TimezoneOption(
    value: 'Europe/Lisbon',
    label: 'UTC+01:00 Western European Time - Lisbon, Porto',
    searchText: 'Europe/Lisbon Atlantic/Madeira Europe/Lisbon Portugal WET Western European Time Portugal PT Lisbon Porto Amadora Braga',
    offsetMinutes: 60,
  ),
  TimezoneOption(
    value: 'Atlantic/Faroe',
    label: 'UTC+01:00 Western European Time - Tórshavn',
    searchText: 'Atlantic/Faroe Atlantic/Faroe Atlantic/Faeroe Western European Time Faroe Islands FO Tórshavn',
    offsetMinutes: 60,
  ),
  TimezoneOption(
    value: 'Africa/Bujumbura',
    label: 'UTC+02:00 Central Africa Time - Bujumbura, Gitega',
    searchText: 'Africa/Bujumbura Africa/Bujumbura Central Africa Time Burundi BI Bujumbura Gitega Ngozi Rumonge',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Africa/Gaborone',
    label: 'UTC+02:00 Central Africa Time - Gaborone, Francistown',
    searchText: 'Africa/Gaborone Africa/Gaborone Central Africa Time Botswana BW Gaborone Francistown Mogoditshane Maun',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Africa/Harare',
    label: 'UTC+02:00 Central Africa Time - Harare, Bulawayo',
    searchText: 'Africa/Harare Africa/Harare Central Africa Time Zimbabwe ZW Harare Bulawayo Chitungwiza Mutare',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Africa/Juba',
    label: 'UTC+02:00 Central Africa Time - Juba, Winejok',
    searchText: 'Africa/Juba Africa/Juba Central Africa Time South Sudan SS Juba Winejok Yei Malakal',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Africa/Khartoum',
    label: 'UTC+02:00 Central Africa Time - Khartoum, Omdurman',
    searchText: 'Africa/Khartoum Africa/Khartoum Central Africa Time Sudan SD Khartoum Omdurman Khartoum North Nyala',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Africa/Kigali',
    label: 'UTC+02:00 Central Africa Time - Kigali, Gisenyi',
    searchText: 'Africa/Kigali Africa/Kigali Central Africa Time Rwanda RW Kigali Gisenyi Musanze Nyagatare',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Africa/Blantyre',
    label: 'UTC+02:00 Central Africa Time - Lilongwe, Blantyre',
    searchText: 'Africa/Blantyre Africa/Blantyre Central Africa Time Malawi MW Lilongwe Blantyre Mzuzu Zomba',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Africa/Lubumbashi',
    label: 'UTC+02:00 Central Africa Time - Lubumbashi, Mbuji-Mayi',
    searchText: 'Africa/Lubumbashi Africa/Lubumbashi Central Africa Time Democratic Republic of the Congo CD Lubumbashi Mbuji-Mayi Kananga Kisangani',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Africa/Lusaka',
    label: 'UTC+02:00 Central Africa Time - Lusaka, Kitwe',
    searchText: 'Africa/Lusaka Africa/Lusaka Central Africa Time Zambia ZM Lusaka Kitwe Ndola Chipata',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Africa/Maputo',
    label: 'UTC+02:00 Central Africa Time - Maputo, Matola',
    searchText: 'Africa/Maputo Africa/Maputo Africa/Blantyre Africa/Bujumbura Africa/Gaborone Africa/Harare Africa/Kigali Africa/Lubumbashi Africa/Lusaka Central Africa Time Mozambique MZ Maputo Matola Nampula Beira',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Africa/Windhoek',
    label: 'UTC+02:00 Central Africa Time - Windhoek, Rundu',
    searchText: 'Africa/Windhoek Africa/Windhoek Central Africa Time Namibia NA Windhoek Rundu Walvis Bay Swakopmund',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Andorra',
    label: 'UTC+02:00 Central European Time - Andorra la Vella, les Escaldes',
    searchText: 'Europe/Andorra Europe/Andorra Central European Time Andorra AD Andorra la Vella les Escaldes',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Belgrade',
    label: 'UTC+02:00 Central European Time - Belgrade, Niš',
    searchText: 'Europe/Belgrade Europe/Belgrade Europe/Ljubljana Europe/Podgorica Europe/Sarajevo Europe/Skopje Europe/Zagreb Central European Time Serbia RS Belgrade Niš Novi Sad Zemun',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Berlin',
    label: 'UTC+02:00 Central European Time - Berlin, Hamburg',
    searchText: 'Europe/Berlin Europe/Berlin Europe/Busingen Arctic/Longyearbyen Europe/Copenhagen Europe/Oslo Europe/Stockholm Atlantic/Jan_Mayen Central European Time Germany DE Berlin Hamburg Munich Köln',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Bratislava',
    label: 'UTC+02:00 Central European Time - Bratislava, Košice',
    searchText: 'Europe/Bratislava Europe/Bratislava Central European Time Slovakia SK Bratislava Košice Petržalka Nitra',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Brussels',
    label: 'UTC+02:00 Central European Time - Brussels, Antwerpen',
    searchText: 'Europe/Brussels Europe/Brussels CET MET Europe/Amsterdam Europe/Luxembourg Central European Time Belgium BE Brussels Antwerpen Gent Charleroi',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Budapest',
    label: 'UTC+02:00 Central European Time - Budapest, Debrecen',
    searchText: 'Europe/Budapest Europe/Budapest Central European Time Hungary HU Budapest Debrecen Szeged Miskolc',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Copenhagen',
    label: 'UTC+02:00 Central European Time - Copenhagen, Århus',
    searchText: 'Europe/Copenhagen Europe/Copenhagen Central European Time Denmark DK Copenhagen Århus Odense Aalborg',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Gibraltar',
    label: 'UTC+02:00 Central European Time - Gibraltar',
    searchText: 'Europe/Gibraltar Europe/Gibraltar Central European Time Gibraltar GI Gibraltar',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Ljubljana',
    label: 'UTC+02:00 Central European Time - Ljubljana, Maribor',
    searchText: 'Europe/Ljubljana Europe/Ljubljana Central European Time Slovenia SI Ljubljana Maribor Celje Kranj',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Arctic/Longyearbyen',
    label: 'UTC+02:00 Central European Time - Longyearbyen',
    searchText: 'Arctic/Longyearbyen Arctic/Longyearbyen Central European Time Svalbard and Jan Mayen SJ Longyearbyen',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Luxembourg',
    label: 'UTC+02:00 Central European Time - Luxembourg, Esch-sur-Alzette',
    searchText: 'Europe/Luxembourg Europe/Luxembourg Central European Time Luxembourg LU Luxembourg Esch-sur-Alzette Dudelange',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Madrid',
    label: 'UTC+02:00 Central European Time - Madrid, Barcelona',
    searchText: 'Europe/Madrid Africa/Ceuta Europe/Madrid Central European Time Spain ES Madrid Barcelona Valencia Zaragoza',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Monaco',
    label: 'UTC+02:00 Central European Time - Monaco, Monte-Carlo',
    searchText: 'Europe/Monaco Europe/Monaco Central European Time Monaco MC Monaco Monte-Carlo',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Oslo',
    label: 'UTC+02:00 Central European Time - Oslo, Bergen',
    searchText: 'Europe/Oslo Europe/Oslo Central European Time Norway NO Oslo Bergen Trondheim Stavanger',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Paris',
    label: 'UTC+02:00 Central European Time - Paris, Marseille',
    searchText: 'Europe/Paris Europe/Paris Europe/Monaco Central European Time France FR Paris Marseille Lyon Toulouse',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Podgorica',
    label: 'UTC+02:00 Central European Time - Podgorica, Nikšić',
    searchText: 'Europe/Podgorica Europe/Podgorica Central European Time Montenegro ME Podgorica Nikšić Herceg Novi Pljevlja',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Prague',
    label: 'UTC+02:00 Central European Time - Prague, Brno',
    searchText: 'Europe/Prague Europe/Prague Europe/Bratislava Central European Time Czechia CZ Prague Brno Ostrava Pilsen',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Rome',
    label: 'UTC+02:00 Central European Time - Rome, Milan',
    searchText: 'Europe/Rome Europe/Rome Europe/San_Marino Europe/Vatican Central European Time Italy IT Rome Milan Naples Turin',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Amsterdam',
    label: 'UTC+02:00 Central European Time - Rotterdam, Amsterdam',
    searchText: 'Europe/Amsterdam Europe/Amsterdam Central European Time The Netherlands NL Rotterdam Amsterdam The Hague Utrecht',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/San_Marino',
    label: 'UTC+02:00 Central European Time - San Marino',
    searchText: 'Europe/San_Marino Europe/San_Marino Central European Time San Marino SM San Marino',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Malta',
    label: 'UTC+02:00 Central European Time - San Pawl il-Baħar, Birkirkara',
    searchText: 'Europe/Malta Europe/Malta Central European Time Malta MT San Pawl il-Baħar Birkirkara Mosta Sliema',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Sarajevo',
    label: 'UTC+02:00 Central European Time - Sarajevo, Banja Luka',
    searchText: 'Europe/Sarajevo Europe/Sarajevo Central European Time Bosnia and Herzegovina BA Sarajevo Banja Luka Zenica Tuzla',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Skopje',
    label: 'UTC+02:00 Central European Time - Skopje, Kumanovo',
    searchText: 'Europe/Skopje Europe/Skopje Central European Time North Macedonia MK Skopje Kumanovo Prilep Bitola',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Stockholm',
    label: 'UTC+02:00 Central European Time - Stockholm, Göteborg',
    searchText: 'Europe/Stockholm Europe/Stockholm Central European Time Sweden SE Stockholm Göteborg Malmö Uppsala',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Tirane',
    label: 'UTC+02:00 Central European Time - Tirana, Durrës',
    searchText: 'Europe/Tirane Europe/Tirane Central European Time Albania AL Tirana Durrës Vlorë Elbasan',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Vaduz',
    label: 'UTC+02:00 Central European Time - Vaduz',
    searchText: 'Europe/Vaduz Europe/Vaduz Central European Time Liechtenstein LI Vaduz',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Vatican',
    label: 'UTC+02:00 Central European Time - Vatican City',
    searchText: 'Europe/Vatican Europe/Vatican Central European Time Vatican VA Vatican City',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Vienna',
    label: 'UTC+02:00 Central European Time - Vienna, Graz',
    searchText: 'Europe/Vienna Europe/Vienna Central European Time Austria AT Vienna Graz Linz Favoriten',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Warsaw',
    label: 'UTC+02:00 Central European Time - Warsaw, Łódź',
    searchText: 'Europe/Warsaw Europe/Warsaw Poland Central European Time Poland PL Warsaw Łódź Kraków Wrocław',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Zagreb',
    label: 'UTC+02:00 Central European Time - Zagreb, Split',
    searchText: 'Europe/Zagreb Europe/Zagreb Central European Time Croatia HR Zagreb Split Rijeka Osijek',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Zurich',
    label: 'UTC+02:00 Central European Time - Zürich, Genève',
    searchText: 'Europe/Zurich Europe/Zurich Europe/Busingen Europe/Vaduz Central European Time Switzerland CH Zürich Genève Basel Lausanne',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Europe/Kaliningrad',
    label: 'UTC+02:00 Eastern European Time - Kaliningrad, Chernyakhovsk',
    searchText: 'Europe/Kaliningrad Europe/Kaliningrad Eastern European Time Russia RU Kaliningrad Chernyakhovsk Sovetsk Baltiysk',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Africa/Tripoli',
    label: 'UTC+02:00 Eastern European Time - Tripoli, Benghazi',
    searchText: 'Africa/Tripoli Africa/Tripoli Libya Eastern European Time Libya LY Tripoli Benghazi Misratah Zliten',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Antarctica/Troll',
    label: 'UTC+02:00 Greenwich Mean Time - Troll',
    searchText: 'Antarctica/Troll Antarctica/Troll Greenwich Mean Time Antarctica AQ Troll',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Africa/Johannesburg',
    label: 'UTC+02:00 South Africa Time - Johannesburg, Cape Town',
    searchText: 'Africa/Johannesburg Africa/Johannesburg Africa/Maseru Africa/Mbabane South Africa Time South Africa ZA Johannesburg Cape Town Durban Pretoria',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Africa/Mbabane',
    label: 'UTC+02:00 South Africa Time - Manzini, Mbabane',
    searchText: 'Africa/Mbabane Africa/Mbabane South Africa Time Eswatini SZ Manzini Mbabane Lobamba',
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Africa/Maseru',
    label: 'UTC+02:00 South Africa Time - Maseru, Maputsoe',
    searchText: "Africa/Maseru Africa/Maseru South Africa Time Lesotho LS Maseru Maputsoe Mohale's Hoek Mafeteng",
    offsetMinutes: 120,
  ),
  TimezoneOption(
    value: 'Asia/Kuwait',
    label: 'UTC+03:00 Arabian Time - Al Aḩmadī, Ḩawallī',
    searchText: 'Asia/Kuwait Asia/Kuwait Arabian Time Kuwait KW Al Aḩmadī Ḩawallī As Sālimīyah Şabāḩ as Sālim',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Asia/Bahrain',
    label: 'UTC+03:00 Arabian Time - Al Muharraq, Manama',
    searchText: 'Asia/Bahrain Asia/Bahrain Arabian Time Bahrain BH Al Muharraq Manama Madīnat Ḩamad Ar Rifā‘',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Asia/Baghdad',
    label: 'UTC+03:00 Arabian Time - Baghdad, Al Mawşil al Jadīdah',
    searchText: 'Asia/Baghdad Asia/Baghdad Arabian Time Iraq IQ Baghdad Al Mawşil al Jadīdah Al Başrah al Qadīmah Mosul',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Asia/Qatar',
    label: 'UTC+03:00 Arabian Time - Doha, Ar Rayyān',
    searchText: 'Asia/Qatar Asia/Qatar Asia/Bahrain Arabian Time Qatar QA Doha Ar Rayyān Al Maţār al ‘Atīq Al Manşūrah',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Asia/Riyadh',
    label: 'UTC+03:00 Arabian Time - Jeddah, Riyadh',
    searchText: 'Asia/Riyadh Asia/Riyadh Antarctica/Syowa Asia/Aden Asia/Kuwait Arabian Time Saudi Arabia SA Jeddah Riyadh Makkah Madinah',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Asia/Aden',
    label: 'UTC+03:00 Arabian Time - Sanaa, Aden',
    searchText: 'Asia/Aden Asia/Aden Arabian Time Yemen YE Sanaa Aden Taiz Ibb',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Asia/Amman',
    label: 'UTC+03:00 Asia/Amman - Amman, Zarqa',
    searchText: 'Asia/Amman Asia/Amman Asia/Amman Jordan JO Amman Zarqa Irbid Russeifa',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Asia/Damascus',
    label: 'UTC+03:00 Asia/Damascus - Aleppo, Damascus',
    searchText: 'Asia/Damascus Asia/Damascus Asia/Damascus Syria SY Aleppo Damascus Homs Latakia',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Africa/Addis_Ababa',
    label: 'UTC+03:00 East Africa Time - Addis Ababa, Jijiga',
    searchText: "Africa/Addis_Ababa Africa/Addis_Ababa East Africa Time Ethiopia ET Addis Ababa Jijiga Gonder Mek'ele",
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Indian/Antananarivo',
    label: 'UTC+03:00 East Africa Time - Antananarivo, Toamasina',
    searchText: 'Indian/Antananarivo Indian/Antananarivo East Africa Time Madagascar MG Antananarivo Toamasina Antsirabe Mahajanga',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Africa/Asmara',
    label: 'UTC+03:00 East Africa Time - Asmara, Keren',
    searchText: 'Africa/Asmara Africa/Asmara East Africa Time Eritrea ER Asmara Keren Himora Massawa',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Africa/Dar_es_Salaam',
    label: 'UTC+03:00 East Africa Time - Dar es Salaam, Mwanza',
    searchText: 'Africa/Dar_es_Salaam Africa/Dar_es_Salaam East Africa Time Tanzania TZ Dar es Salaam Mwanza Dodoma Zanzibar',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Africa/Djibouti',
    label: 'UTC+03:00 East Africa Time - Djibouti, Ali Sabih',
    searchText: 'Africa/Djibouti Africa/Djibouti East Africa Time Djibouti DJ Djibouti Ali Sabih Dikhil Tadjoura',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Africa/Kampala',
    label: 'UTC+03:00 East Africa Time - Kampala, Nansana',
    searchText: 'Africa/Kampala Africa/Kampala East Africa Time Uganda UG Kampala Nansana Kira Bunamwaya',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Indian/Mayotte',
    label: 'UTC+03:00 East Africa Time - Mamoudzou, Koungou',
    searchText: 'Indian/Mayotte Indian/Mayotte East Africa Time Mayotte YT Mamoudzou Koungou Labattoir Kaouéni',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Africa/Mogadishu',
    label: 'UTC+03:00 East Africa Time - Mogadishu, Borama',
    searchText: 'Africa/Mogadishu Africa/Mogadishu East Africa Time Somalia SO Mogadishu Borama Hargeysa Berbera',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Indian/Comoro',
    label: 'UTC+03:00 East Africa Time - Moroni, Moutsamoudou',
    searchText: 'Indian/Comoro Indian/Comoro East Africa Time Comoros KM Moroni Moutsamoudou Fomboni',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Africa/Nairobi',
    label: 'UTC+03:00 East Africa Time - Nairobi, Kakamega',
    searchText: 'Africa/Nairobi Africa/Nairobi Africa/Addis_Ababa Africa/Asmara Africa/Dar_es_Salaam Africa/Djibouti Africa/Kampala Africa/Mogadishu Indian/Antananarivo Indian/Comoro Indian/Mayotte Africa/Asmera East Africa Time Kenya KE Nairobi Kakamega Mombasa Nakuru',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Europe/Athens',
    label: 'UTC+03:00 Eastern European Time - Athens, Thessaloníki',
    searchText: 'Europe/Athens Europe/Athens EET Eastern European Time Greece GR Athens Thessaloníki Pátra Piraeus',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Asia/Beirut',
    label: 'UTC+03:00 Eastern European Time - Beirut, Ra’s Bayrūt',
    searchText: 'Asia/Beirut Asia/Beirut Eastern European Time Lebanon LB Beirut Ra’s Bayrūt Tripoli Sidon',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Europe/Bucharest',
    label: 'UTC+03:00 Eastern European Time - Bucharest, Sector 3',
    searchText: 'Europe/Bucharest Europe/Bucharest Eastern European Time Romania RO Bucharest Sector 3 Iaşi Sector 6',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Africa/Cairo',
    label: 'UTC+03:00 Eastern European Time - Cairo, Alexandria',
    searchText: 'Africa/Cairo Africa/Cairo Egypt Eastern European Time Egypt EG Cairo Alexandria Giza Shubrā al Khaymah',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Europe/Chisinau',
    label: 'UTC+03:00 Eastern European Time - Chisinau, Tiraspol',
    searchText: 'Europe/Chisinau Europe/Chisinau Europe/Tiraspol Eastern European Time Moldova MD Chisinau Tiraspol Bălţi Bender',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Asia/Hebron',
    label: 'UTC+03:00 Eastern European Time - East Jerusalem, Gaza',
    searchText: 'Asia/Hebron Asia/Gaza Asia/Hebron Eastern European Time Palestinian Territory PS East Jerusalem Gaza Khān Yūnis Jabālyā',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Europe/Helsinki',
    label: 'UTC+03:00 Eastern European Time - Helsinki, Espoo',
    searchText: 'Europe/Helsinki Europe/Helsinki Europe/Mariehamn Eastern European Time Finland FI Helsinki Espoo Tampere Vantaa',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Europe/Kyiv',
    label: 'UTC+03:00 Eastern European Time - Kyiv, Kharkiv',
    searchText: 'Europe/Kyiv Europe/Kyiv Europe/Uzhgorod Europe/Zaporozhye Europe/Kiev Eastern European Time Ukraine UA Kyiv Kharkiv Odesa Dnipro',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Europe/Mariehamn',
    label: 'UTC+03:00 Eastern European Time - Mariehamn',
    searchText: 'Europe/Mariehamn Europe/Mariehamn Eastern European Time Aland Islands AX Mariehamn',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Asia/Nicosia',
    label: 'UTC+03:00 Eastern European Time - Nicosia, Limassol',
    searchText: 'Asia/Nicosia Asia/Famagusta Asia/Nicosia Europe/Nicosia Eastern European Time Cyprus CY Nicosia Limassol Larnaca Stróvolos',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Europe/Riga',
    label: 'UTC+03:00 Eastern European Time - Riga, Daugavpils',
    searchText: 'Europe/Riga Europe/Riga Eastern European Time Latvia LV Riga Daugavpils Liepāja Jelgava',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Europe/Sofia',
    label: 'UTC+03:00 Eastern European Time - Sofia, Plovdiv',
    searchText: 'Europe/Sofia Europe/Sofia Eastern European Time Bulgaria BG Sofia Plovdiv Varna Burgas',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Europe/Tallinn',
    label: 'UTC+03:00 Eastern European Time - Tallinn, Tartu',
    searchText: 'Europe/Tallinn Europe/Tallinn Eastern European Time Estonia EE Tallinn Tartu Narva Pärnu',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Europe/Vilnius',
    label: 'UTC+03:00 Eastern European Time - Vilnius, Kaunas',
    searchText: 'Europe/Vilnius Europe/Vilnius Eastern European Time Lithuania LT Vilnius Kaunas Klaipėda Šiauliai',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Asia/Jerusalem',
    label: 'UTC+03:00 Israel Time - Jerusalem, Tel Aviv',
    searchText: 'Asia/Jerusalem Asia/Jerusalem Israel Asia/Tel_Aviv Israel Time Israel IL Jerusalem Tel Aviv West Jerusalem Haifa',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Europe/Minsk',
    label: "UTC+03:00 Moscow Time - Minsk, Homyel'",
    searchText: "Europe/Minsk Europe/Minsk Moscow Time Belarus BY Minsk Homyel' Hrodna Vitebsk",
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Europe/Moscow',
    label: 'UTC+03:00 Moscow Time - Moscow, Saint Petersburg',
    searchText: 'Europe/Moscow Europe/Kirov Europe/Moscow Europe/Volgograd W-SU Moscow Time Russia RU Moscow Saint Petersburg Nizhniy Novgorod Kazan',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Europe/Simferopol',
    label: 'UTC+03:00 Moscow Time - Sevastopol, Simferopol',
    searchText: 'Europe/Simferopol Europe/Simferopol Moscow Time Ukraine UA Sevastopol Simferopol Kerch Yevpatoriya',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Antarctica/Syowa',
    label: 'UTC+03:00 Syowa Time - Syowa',
    searchText: 'Antarctica/Syowa Antarctica/Syowa Syowa Time Antarctica AQ Syowa',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Europe/Istanbul',
    label: 'UTC+03:00 Turkey Time - Istanbul, Ankara',
    searchText: 'Europe/Istanbul Europe/Istanbul Turkey Asia/Istanbul Turkey Time Turkey TR Istanbul Ankara Bursa İzmir',
    offsetMinutes: 180,
  ),
  TimezoneOption(
    value: 'Asia/Tehran',
    label: 'UTC+03:30 Iran Time - Tehran, Mashhad',
    searchText: 'Asia/Tehran Asia/Tehran Iran Iran Time Iran IR Tehran Mashhad Isfahan Karaj',
    offsetMinutes: 210,
  ),
  TimezoneOption(
    value: 'Asia/Yerevan',
    label: 'UTC+04:00 Armenia Time - Yerevan, Malatia-Sebastia',
    searchText: 'Asia/Yerevan Asia/Yerevan Armenia Time Armenia AM Yerevan Malatia-Sebastia Shengavit Nor Nork',
    offsetMinutes: 240,
  ),
  TimezoneOption(
    value: 'Asia/Baku',
    label: 'UTC+04:00 Azerbaijan Time - Baku, Sumqayıt',
    searchText: 'Asia/Baku Asia/Baku Azerbaijan Time Azerbaijan AZ Baku Sumqayıt Ganja Lankaran',
    offsetMinutes: 240,
  ),
  TimezoneOption(
    value: 'Asia/Tbilisi',
    label: 'UTC+04:00 Georgia Time - Tbilisi, Batumi',
    searchText: 'Asia/Tbilisi Asia/Tbilisi Georgia Time Georgia GE Tbilisi Batumi Kutaisi Rustavi',
    offsetMinutes: 240,
  ),
  TimezoneOption(
    value: 'Asia/Dubai',
    label: 'UTC+04:00 Gulf Time - Dubai, Abu Dhabi',
    searchText: 'Asia/Dubai Asia/Dubai Asia/Muscat Indian/Mahe Indian/Reunion Gulf Time United Arab Emirates AE Dubai Abu Dhabi Sharjah Al Ain City',
    offsetMinutes: 240,
  ),
  TimezoneOption(
    value: 'Asia/Muscat',
    label: 'UTC+04:00 Gulf Time - Muscat, Seeb',
    searchText: 'Asia/Muscat Asia/Muscat Gulf Time Oman OM Muscat Seeb Bawshar ‘Ibrī',
    offsetMinutes: 240,
  ),
  TimezoneOption(
    value: 'Indian/Mauritius',
    label: 'UTC+04:00 Mauritius Time - Port Louis, Vacoas',
    searchText: 'Indian/Mauritius Indian/Mauritius Mauritius Time Mauritius MU Port Louis Vacoas Beau Bassin-Rose Hill Curepipe',
    offsetMinutes: 240,
  ),
  TimezoneOption(
    value: 'Indian/Reunion',
    label: 'UTC+04:00 Réunion Time - Saint-Denis, Saint-Paul',
    searchText: 'Indian/Reunion Indian/Reunion Réunion Time Reunion RE Saint-Denis Saint-Paul Saint-Pierre Le Tampon',
    offsetMinutes: 240,
  ),
  TimezoneOption(
    value: 'Europe/Samara',
    label: 'UTC+04:00 Samara Time - Samara, Saratov',
    searchText: 'Europe/Samara Europe/Astrakhan Europe/Samara Europe/Saratov Europe/Ulyanovsk Samara Time Russia RU Samara Saratov Tolyatti Izhevsk',
    offsetMinutes: 240,
  ),
  TimezoneOption(
    value: 'Indian/Mahe',
    label: 'UTC+04:00 Seychelles Time - Victoria',
    searchText: 'Indian/Mahe Indian/Mahe Seychelles Time Seychelles SC Victoria',
    offsetMinutes: 240,
  ),
  TimezoneOption(
    value: 'Asia/Kabul',
    label: 'UTC+04:30 Afghanistan Time - Kabul, Herāt',
    searchText: 'Asia/Kabul Asia/Kabul Afghanistan Time Afghanistan AF Kabul Herāt Mazār-e Sharīf Kandahār',
    offsetMinutes: 270,
  ),
  TimezoneOption(
    value: 'Indian/Kerguelen',
    label: 'UTC+05:00 French Southern & Antarctic Time - Port-aux-Français',
    searchText: 'Indian/Kerguelen Indian/Kerguelen French Southern & Antarctic Time French Southern Territories TF Port-aux-Français',
    offsetMinutes: 300,
  ),
  TimezoneOption(
    value: 'Asia/Almaty',
    label: 'UTC+05:00 Kazakhstan Time - Almaty, Shymkent',
    searchText: 'Asia/Almaty Asia/Almaty Asia/Aqtau Asia/Aqtobe Asia/Atyrau Asia/Oral Asia/Qostanay Asia/Qyzylorda Kazakhstan Time Kazakhstan KZ Almaty Shymkent Aktobe Karagandy',
    offsetMinutes: 300,
  ),
  TimezoneOption(
    value: 'Indian/Maldives',
    label: 'UTC+05:00 Maldives Time - Male',
    searchText: 'Indian/Maldives Indian/Maldives Indian/Kerguelen Maldives Time Maldives MV Male',
    offsetMinutes: 300,
  ),
  TimezoneOption(
    value: 'Antarctica/Mawson',
    label: 'UTC+05:00 Mawson Time - Mawson, Vostok',
    searchText: 'Antarctica/Mawson Antarctica/Mawson Antarctica/Vostok Mawson Time Antarctica AQ Mawson Vostok',
    offsetMinutes: 300,
  ),
  TimezoneOption(
    value: 'Asia/Karachi',
    label: 'UTC+05:00 Pakistan Time - Lahore, Karachi',
    searchText: 'Asia/Karachi Asia/Karachi Pakistan Time Pakistan PK Lahore Karachi Peshawar Faisalabad',
    offsetMinutes: 300,
  ),
  TimezoneOption(
    value: 'Asia/Dushanbe',
    label: 'UTC+05:00 Tajikistan Time - Dushanbe, Isfara',
    searchText: 'Asia/Dushanbe Asia/Dushanbe Tajikistan Time Tajikistan TJ Dushanbe Isfara Istaravshan Kŭlob',
    offsetMinutes: 300,
  ),
  TimezoneOption(
    value: 'Asia/Ashgabat',
    label: 'UTC+05:00 Turkmenistan Time - Ashgabat, Türkmenabat',
    searchText: 'Asia/Ashgabat Asia/Ashgabat Asia/Ashkhabad Turkmenistan Time Turkmenistan TM Ashgabat Türkmenabat Daşoguz Mary',
    offsetMinutes: 300,
  ),
  TimezoneOption(
    value: 'Asia/Tashkent',
    label: 'UTC+05:00 Uzbekistan Time - Tashkent, Andijon',
    searchText: 'Asia/Tashkent Asia/Samarkand Asia/Tashkent Uzbekistan Time Uzbekistan UZ Tashkent Andijon Namangan Samarkand',
    offsetMinutes: 300,
  ),
  TimezoneOption(
    value: 'Asia/Yekaterinburg',
    label: 'UTC+05:00 Yekaterinburg Time - Yekaterinburg, Chelyabinsk',
    searchText: 'Asia/Yekaterinburg Asia/Yekaterinburg Yekaterinburg Time Russia RU Yekaterinburg Chelyabinsk Ufa Perm',
    offsetMinutes: 300,
  ),
  TimezoneOption(
    value: 'Asia/Colombo',
    label: 'UTC+05:30 India Time - Colombo, Dehiwala-Mount Lavinia',
    searchText: 'Asia/Colombo Asia/Colombo India Time Sri Lanka LK Colombo Dehiwala-Mount Lavinia Maharagama Jaffna',
    offsetMinutes: 330,
  ),
  TimezoneOption(
    value: 'Asia/Kolkata',
    label: 'UTC+05:30 India Time - Mumbai, Delhi',
    searchText: 'Asia/Kolkata Asia/Kolkata Asia/Calcutta India Time India IN Mumbai Delhi Bengaluru Hyderabad',
    offsetMinutes: 330,
  ),
  TimezoneOption(
    value: 'Asia/Kathmandu',
    label: 'UTC+05:45 Nepal Time - Kathmandu, Pokhara',
    searchText: 'Asia/Kathmandu Asia/Kathmandu Asia/Katmandu Nepal Time Nepal NP Kathmandu Pokhara Bharatpur Pātan',
    offsetMinutes: 345,
  ),
  TimezoneOption(
    value: 'Asia/Dhaka',
    label: 'UTC+06:00 Bangladesh Time - Dhaka, Chattogram',
    searchText: 'Asia/Dhaka Asia/Dhaka Asia/Dacca Bangladesh Time Bangladesh BD Dhaka Chattogram Gazipur Khulna',
    offsetMinutes: 360,
  ),
  TimezoneOption(
    value: 'Asia/Thimphu',
    label: 'UTC+06:00 Bhutan Time - Thimphu, Phuntsholing',
    searchText: 'Asia/Thimphu Asia/Thimphu Asia/Thimbu Bhutan Time Bhutan BT Thimphu Phuntsholing Tsirang Punākha',
    offsetMinutes: 360,
  ),
  TimezoneOption(
    value: 'Asia/Urumqi',
    label: 'UTC+06:00 China Time - Ürümqi, Shihezi',
    searchText: 'Asia/Urumqi Asia/Urumqi Asia/Kashgar China Time China CN Ürümqi Shihezi Korla Aqsu',
    offsetMinutes: 360,
  ),
  TimezoneOption(
    value: 'Indian/Chagos',
    label: 'UTC+06:00 Indian Ocean Time - Chagos',
    searchText: 'Indian/Chagos Indian/Chagos Indian Ocean Time British Indian Ocean Territory IO Chagos',
    offsetMinutes: 360,
  ),
  TimezoneOption(
    value: 'Asia/Bishkek',
    label: 'UTC+06:00 Kyrgyzstan Time - Bishkek, Osh',
    searchText: 'Asia/Bishkek Asia/Bishkek Kyrgyzstan Time Kyrgyzstan KG Bishkek Osh Jalal-Abad Karakol',
    offsetMinutes: 360,
  ),
  TimezoneOption(
    value: 'Asia/Omsk',
    label: 'UTC+06:00 Omsk Time - Omsk, Tara',
    searchText: 'Asia/Omsk Asia/Omsk Omsk Time Russia RU Omsk Tara Kalachinsk Isil’kul’',
    offsetMinutes: 360,
  ),
  TimezoneOption(
    value: 'Indian/Cocos',
    label: 'UTC+06:30 Cocos Islands Time - West Island',
    searchText: 'Indian/Cocos Indian/Cocos Cocos Islands Time Cocos Islands CC West Island',
    offsetMinutes: 390,
  ),
  TimezoneOption(
    value: 'Asia/Yangon',
    label: 'UTC+06:30 Myanmar Time - Yangon, Mandalay',
    searchText: 'Asia/Yangon Asia/Yangon Indian/Cocos Asia/Rangoon Myanmar Time Myanmar MM Yangon Mandalay Nay Pyi Taw Hlaingthaya Township',
    offsetMinutes: 390,
  ),
  TimezoneOption(
    value: 'Indian/Christmas',
    label: 'UTC+07:00 Christmas Island Time - Flying Fish Cove',
    searchText: 'Indian/Christmas Indian/Christmas Christmas Island Time Christmas Island CX Flying Fish Cove',
    offsetMinutes: 420,
  ),
  TimezoneOption(
    value: 'Antarctica/Davis',
    label: 'UTC+07:00 Davis Time - Davis',
    searchText: 'Antarctica/Davis Antarctica/Davis Davis Time Antarctica AQ Davis',
    offsetMinutes: 420,
  ),
  TimezoneOption(
    value: 'Asia/Hovd',
    label: 'UTC+07:00 Hovd Time - Ulaangom, Khovd',
    searchText: 'Asia/Hovd Asia/Hovd Hovd Time Mongolia MN Ulaangom Khovd Ölgii Altai',
    offsetMinutes: 420,
  ),
  TimezoneOption(
    value: 'Asia/Bangkok',
    label: 'UTC+07:00 Indochina Time - Bangkok, Samut Prakan',
    searchText: 'Asia/Bangkok Asia/Bangkok Asia/Phnom_Penh Asia/Vientiane Indian/Christmas Indochina Time Thailand TH Bangkok Samut Prakan Mueang Nonthaburi Chon Buri',
    offsetMinutes: 420,
  ),
  TimezoneOption(
    value: 'Asia/Ho_Chi_Minh',
    label: 'UTC+07:00 Indochina Time - Ho Chi Minh City, Cần Thơ',
    searchText: 'Asia/Ho_Chi_Minh Asia/Ho_Chi_Minh Asia/Saigon Indochina Time Vietnam VN Ho Chi Minh City Cần Thơ Da Nang Biên Hòa',
    offsetMinutes: 420,
  ),
  TimezoneOption(
    value: 'Asia/Phnom_Penh',
    label: 'UTC+07:00 Indochina Time - Phnom Penh, Takeo',
    searchText: 'Asia/Phnom_Penh Asia/Phnom_Penh Indochina Time Cambodia KH Phnom Penh Takeo Siem Reap Battambang',
    offsetMinutes: 420,
  ),
  TimezoneOption(
    value: 'Asia/Vientiane',
    label: 'UTC+07:00 Indochina Time - Vientiane, Savannakhet',
    searchText: 'Asia/Vientiane Asia/Vientiane Indochina Time Laos LA Vientiane Savannakhet Pakse Thakhèk',
    offsetMinutes: 420,
  ),
  TimezoneOption(
    value: 'Asia/Novosibirsk',
    label: 'UTC+07:00 Novosibirsk Time - Novosibirsk, Krasnoyarsk',
    searchText: 'Asia/Novosibirsk Asia/Barnaul Asia/Krasnoyarsk Asia/Novokuznetsk Asia/Novosibirsk Asia/Tomsk Novosibirsk Time Russia RU Novosibirsk Krasnoyarsk Barnaul Tomsk',
    offsetMinutes: 420,
  ),
  TimezoneOption(
    value: 'Asia/Jakarta',
    label: 'UTC+07:00 Western Indonesia Time - Jakarta, Surabaya',
    searchText: 'Asia/Jakarta Asia/Jakarta Asia/Pontianak Western Indonesia Time Indonesia ID Jakarta Surabaya Bekasi Bandung',
    offsetMinutes: 420,
  ),
  TimezoneOption(
    value: 'Antarctica/Casey',
    label: 'UTC+08:00 Australian Western Time - Casey',
    searchText: 'Antarctica/Casey Antarctica/Casey Australian Western Time Antarctica AQ Casey',
    offsetMinutes: 480,
  ),
  TimezoneOption(
    value: 'Australia/Perth',
    label: 'UTC+08:00 Australian Western Time - Perth, Mandurah',
    searchText: 'Australia/Perth Australia/Perth Australia/West Australian Western Time Australia AU Perth Mandurah Bunbury Geraldton',
    offsetMinutes: 480,
  ),
  TimezoneOption(
    value: 'Asia/Brunei',
    label: 'UTC+08:00 Brunei Time - Bandar Seri Begawan, Sengkurong',
    searchText: 'Asia/Brunei Asia/Brunei Brunei Time Brunei BN Bandar Seri Begawan Sengkurong Mentiri Kuala Belait',
    offsetMinutes: 480,
  ),
  TimezoneOption(
    value: 'Asia/Makassar',
    label: 'UTC+08:00 Central Indonesia Time - Makassar, Samarinda',
    searchText: 'Asia/Makassar Asia/Makassar Asia/Ujung_Pandang Central Indonesia Time Indonesia ID Makassar Samarinda Denpasar Balikpapan',
    offsetMinutes: 480,
  ),
  TimezoneOption(
    value: 'Asia/Macau',
    label: 'UTC+08:00 China Time - Macau, Taipa',
    searchText: 'Asia/Macau Asia/Macau Asia/Macao China Time Macao MO Macau Taipa Sé Luhuan',
    offsetMinutes: 480,
  ),
  TimezoneOption(
    value: 'Asia/Shanghai',
    label: 'UTC+08:00 China Time - Shanghai, Beijing',
    searchText: 'Asia/Shanghai Asia/Shanghai PRC Asia/Chongqing Asia/Harbin Asia/Chungking China Time China CN Shanghai Beijing Shenzhen Guangzhou',
    offsetMinutes: 480,
  ),
  TimezoneOption(
    value: 'Asia/Hong_Kong',
    label: 'UTC+08:00 Hong Kong Time - Hong Kong, New Territories',
    searchText: 'Asia/Hong_Kong Asia/Hong_Kong Hongkong Hong Kong Time Hong Kong HK Hong Kong New Territories Kowloon Hong Kong Island',
    offsetMinutes: 480,
  ),
  TimezoneOption(
    value: 'Asia/Irkutsk',
    label: 'UTC+08:00 Irkutsk Time - Irkutsk, Ulan-Ude',
    searchText: 'Asia/Irkutsk Asia/Irkutsk Irkutsk Time Russia RU Irkutsk Ulan-Ude Bratsk Angarsk',
    offsetMinutes: 480,
  ),
  TimezoneOption(
    value: 'Asia/Kuala_Lumpur',
    label: 'UTC+08:00 Malaysia Time - Kuala Lumpur, Johor Bahru',
    searchText: 'Asia/Kuala_Lumpur Asia/Kuala_Lumpur Asia/Kuching Asia/Brunei Malaysia Time Malaysia MY Kuala Lumpur Johor Bahru Kampung Baru Subang Petaling Jaya',
    offsetMinutes: 480,
  ),
  TimezoneOption(
    value: 'Asia/Manila',
    label: 'UTC+08:00 Philippine Time - Quezon City, Davao',
    searchText: 'Asia/Manila Asia/Manila Philippine Time Philippines PH Quezon City Davao Caloocan City Manila',
    offsetMinutes: 480,
  ),
  TimezoneOption(
    value: 'Asia/Singapore',
    label: 'UTC+08:00 Singapore Time - Singapore, Ulu Bedok',
    searchText: 'Asia/Singapore Asia/Singapore Singapore Asia/Kuala_Lumpur Singapore Time Singapore SG Singapore Ulu Bedok Bedok New Town Tampines Estate',
    offsetMinutes: 480,
  ),
  TimezoneOption(
    value: 'Asia/Taipei',
    label: 'UTC+08:00 Taiwan Time - Taipei, New Taipei City',
    searchText: 'Asia/Taipei Asia/Taipei ROC Taiwan Time Taiwan TW Taipei New Taipei City Taichung Kaohsiung',
    offsetMinutes: 480,
  ),
  TimezoneOption(
    value: 'Asia/Ulaanbaatar',
    label: 'UTC+08:00 Ulaanbaatar Time - Ulan Bator, Erdenet',
    searchText: 'Asia/Ulaanbaatar Asia/Ulaanbaatar Asia/Choibalsan Asia/Ulan_Bator Ulaanbaatar Time Mongolia MN Ulan Bator Erdenet Darhan Choibalsan',
    offsetMinutes: 480,
  ),
  TimezoneOption(
    value: 'Australia/Eucla',
    label: 'UTC+08:45 Australian Central Western Time - Eucla',
    searchText: 'Australia/Eucla Australia/Eucla Australian Central Western Time Australia AU Eucla',
    offsetMinutes: 525,
  ),
  TimezoneOption(
    value: 'Asia/Jayapura',
    label: 'UTC+09:00 Eastern Indonesia Time - Jayapura, Ambon',
    searchText: 'Asia/Jayapura Asia/Jayapura Eastern Indonesia Time Indonesia ID Jayapura Ambon Sorong Ternate',
    offsetMinutes: 540,
  ),
  TimezoneOption(
    value: 'Asia/Tokyo',
    label: 'UTC+09:00 Japan Time - Tokyo, Yokohama',
    searchText: 'Asia/Tokyo Asia/Tokyo Japan Japan Time Japan JP Tokyo Yokohama Osaka Nagoya',
    offsetMinutes: 540,
  ),
  TimezoneOption(
    value: 'Asia/Pyongyang',
    label: 'UTC+09:00 Korean Time - Pyongyang, Hamhŭng',
    searchText: 'Asia/Pyongyang Asia/Pyongyang Korean Time North Korea KP Pyongyang Hamhŭng Namp’o Sunch’ŏn',
    offsetMinutes: 540,
  ),
  TimezoneOption(
    value: 'Asia/Seoul',
    label: 'UTC+09:00 Korean Time - Seoul, Busan',
    searchText: 'Asia/Seoul Asia/Seoul ROK Korean Time South Korea KR Seoul Busan Incheon Daegu',
    offsetMinutes: 540,
  ),
  TimezoneOption(
    value: 'Pacific/Palau',
    label: 'UTC+09:00 Palau Time - Ngerulmud',
    searchText: 'Pacific/Palau Pacific/Palau Palau Time Palau PW Ngerulmud',
    offsetMinutes: 540,
  ),
  TimezoneOption(
    value: 'Asia/Dili',
    label: 'UTC+09:00 Timor-Leste Time - Dili, Maliana',
    searchText: 'Asia/Dili Asia/Dili Timor-Leste Time Timor Leste TL Dili Maliana Suai Likisá',
    offsetMinutes: 540,
  ),
  TimezoneOption(
    value: 'Asia/Chita',
    label: 'UTC+09:00 Yakutsk Time - Chita, Yakutsk',
    searchText: 'Asia/Chita Asia/Chita Asia/Khandyga Asia/Yakutsk Yakutsk Time Russia RU Chita Yakutsk Blagoveshchensk Belogorsk',
    offsetMinutes: 540,
  ),
  TimezoneOption(
    value: 'Australia/Adelaide',
    label: 'UTC+09:30 Australian Central Time - Adelaide, Adelaide Hills',
    searchText: 'Australia/Adelaide Australia/Adelaide Australia/Broken_Hill Australia/South Australia/Yancowinna Australian Central Time Australia AU Adelaide Adelaide Hills Mount Gambier Morphett Vale',
    offsetMinutes: 570,
  ),
  TimezoneOption(
    value: 'Australia/Darwin',
    label: 'UTC+09:30 Australian Central Time - Darwin, Palmerston',
    searchText: 'Australia/Darwin Australia/Darwin Australia/North Australian Central Time Australia AU Darwin Palmerston Alice Springs',
    offsetMinutes: 570,
  ),
  TimezoneOption(
    value: 'Australia/Brisbane',
    label: 'UTC+10:00 Australian Eastern Time - Brisbane, Gold Coast',
    searchText: 'Australia/Brisbane Australia/Brisbane Australia/Lindeman Australia/Queensland Australian Eastern Time Australia AU Brisbane Gold Coast Sunshine Coast Logan City',
    offsetMinutes: 600,
  ),
  TimezoneOption(
    value: 'Australia/Sydney',
    label: 'UTC+10:00 Australian Eastern Time - Sydney, Melbourne',
    searchText: 'Australia/Sydney Antarctica/Macquarie Australia/Hobart Australia/Melbourne Australia/Sydney Australia/Tasmania Australia/Currie Australia/Victoria Australia/ACT Australia/NSW Australia/Canberra Australian Eastern Time Australia AU Sydney Melbourne Newcastle Canberra',
    offsetMinutes: 600,
  ),
  TimezoneOption(
    value: 'Pacific/Guam',
    label: 'UTC+10:00 Chamorro Time - Dededo Village, Yigo Village',
    searchText: 'Pacific/Guam Pacific/Guam Pacific/Saipan Chamorro Time Guam GU Dededo Village Yigo Village Tamuning-Tumon-Harmon Village Tamuning',
    offsetMinutes: 600,
  ),
  TimezoneOption(
    value: 'Pacific/Saipan',
    label: 'UTC+10:00 Chamorro Time - Saipan',
    searchText: 'Pacific/Saipan Pacific/Saipan Chamorro Time Northern Mariana Islands MP Saipan',
    offsetMinutes: 600,
  ),
  TimezoneOption(
    value: 'Pacific/Chuuk',
    label: 'UTC+10:00 Chuuk Time - Chuuk',
    searchText: 'Pacific/Chuuk Pacific/Chuuk Chuuk Time Micronesia FM Chuuk',
    offsetMinutes: 600,
  ),
  TimezoneOption(
    value: 'Antarctica/DumontDUrville',
    label: 'UTC+10:00 Dumont d’Urville Time - DumontDUrville',
    searchText: 'Antarctica/DumontDUrville Antarctica/DumontDUrville Dumont d’Urville Time Antarctica AQ DumontDUrville',
    offsetMinutes: 600,
  ),
  TimezoneOption(
    value: 'Pacific/Port_Moresby',
    label: 'UTC+10:00 Papua New Guinea Time - Port Moresby, Lae',
    searchText: 'Pacific/Port_Moresby Pacific/Port_Moresby Antarctica/DumontDUrville Pacific/Chuuk Pacific/Yap Pacific/Truk Papua New Guinea Time Papua New Guinea PG Port Moresby Lae Mount Hagen Popondetta',
    offsetMinutes: 600,
  ),
  TimezoneOption(
    value: 'Asia/Vladivostok',
    label: 'UTC+10:00 Vladivostok Time - Khabarovsk, Vladivostok',
    searchText: 'Asia/Vladivostok Asia/Ust-Nera Asia/Vladivostok Vladivostok Time Russia RU Khabarovsk Vladivostok Khabarovsk Vtoroy Komsomolsk-on-Amur',
    offsetMinutes: 600,
  ),
  TimezoneOption(
    value: 'Australia/Lord_Howe',
    label: 'UTC+10:30 Lord Howe Time - Lord Howe',
    searchText: 'Australia/Lord_Howe Australia/Lord_Howe Australia/LHI Lord Howe Time Australia AU Lord Howe',
    offsetMinutes: 630,
  ),
  TimezoneOption(
    value: 'Pacific/Bougainville',
    label: 'UTC+11:00 Bougainville Time - Arawa',
    searchText: 'Pacific/Bougainville Pacific/Bougainville Bougainville Time Papua New Guinea PG Arawa',
    offsetMinutes: 660,
  ),
  TimezoneOption(
    value: 'Pacific/Kosrae',
    label: 'UTC+11:00 Kosrae Time - Kosrae, Palikir',
    searchText: 'Pacific/Kosrae Pacific/Kosrae Pacific/Pohnpei Kosrae Time Micronesia FM Kosrae Palikir',
    offsetMinutes: 660,
  ),
  TimezoneOption(
    value: 'Pacific/Noumea',
    label: 'UTC+11:00 New Caledonia Time - Nouméa, Mont-Dore',
    searchText: 'Pacific/Noumea Pacific/Noumea New Caledonia Time New Caledonia NC Nouméa Mont-Dore Dumbéa',
    offsetMinutes: 660,
  ),
  TimezoneOption(
    value: 'Pacific/Norfolk',
    label: 'UTC+11:00 Norfolk Island Time - Kingston',
    searchText: 'Pacific/Norfolk Pacific/Norfolk Norfolk Island Time Norfolk Island NF Kingston',
    offsetMinutes: 660,
  ),
  TimezoneOption(
    value: 'Asia/Sakhalin',
    label: 'UTC+11:00 Sakhalin Time - Yuzhno-Sakhalinsk, Magadan',
    searchText: 'Asia/Sakhalin Asia/Magadan Asia/Sakhalin Asia/Srednekolymsk Sakhalin Time Russia RU Yuzhno-Sakhalinsk Magadan Korsakov Kholmsk',
    offsetMinutes: 660,
  ),
  TimezoneOption(
    value: 'Pacific/Guadalcanal',
    label: 'UTC+11:00 Solomon Islands Time - Honiara, Panatina',
    searchText: 'Pacific/Guadalcanal Pacific/Guadalcanal Pacific/Pohnpei Pacific/Ponape Solomon Islands Time Solomon Islands SB Honiara Panatina Nggosi Tandai',
    offsetMinutes: 660,
  ),
  TimezoneOption(
    value: 'Pacific/Efate',
    label: 'UTC+11:00 Vanuatu Time - Port-Vila',
    searchText: 'Pacific/Efate Pacific/Efate Vanuatu Time Vanuatu VU Port-Vila',
    offsetMinutes: 660,
  ),
  TimezoneOption(
    value: 'Pacific/Fiji',
    label: 'UTC+12:00 Fiji Time - Nasinu, Suva',
    searchText: 'Pacific/Fiji Pacific/Fiji Fiji Time Fiji FJ Nasinu Suva Lautoka Nadi',
    offsetMinutes: 720,
  ),
  TimezoneOption(
    value: 'Pacific/Tarawa',
    label: 'UTC+12:00 Gilbert Islands Time - Tarawa',
    searchText: 'Pacific/Tarawa Pacific/Tarawa Pacific/Funafuti Pacific/Majuro Pacific/Wake Pacific/Wallis Gilbert Islands Time Kiribati KI Tarawa',
    offsetMinutes: 720,
  ),
  TimezoneOption(
    value: 'Asia/Kamchatka',
    label: 'UTC+12:00 Kamchatka Time - Petropavlovsk-Kamchatsky, Yelizovo',
    searchText: 'Asia/Kamchatka Asia/Anadyr Asia/Kamchatka Kamchatka Time Russia RU Petropavlovsk-Kamchatsky Yelizovo Vilyuchinsk Anadyr',
    offsetMinutes: 720,
  ),
  TimezoneOption(
    value: 'Pacific/Majuro',
    label: 'UTC+12:00 Marshall Islands Time - Majuro, Kwajalein',
    searchText: 'Pacific/Majuro Pacific/Kwajalein Pacific/Majuro Kwajalein Marshall Islands Time Marshall Islands MH Majuro Kwajalein',
    offsetMinutes: 720,
  ),
  TimezoneOption(
    value: 'Pacific/Nauru',
    label: 'UTC+12:00 Nauru Time - Yaren',
    searchText: 'Pacific/Nauru Pacific/Nauru Nauru Time Nauru NR Yaren',
    offsetMinutes: 720,
  ),
  TimezoneOption(
    value: 'Pacific/Auckland',
    label: 'UTC+12:00 New Zealand Time - Auckland, Christchurch',
    searchText: 'Pacific/Auckland Pacific/Auckland NZ Antarctica/McMurdo Antarctica/South_Pole New Zealand Time New Zealand NZ Auckland Christchurch Wellington Manukau City',
    offsetMinutes: 720,
  ),
  TimezoneOption(
    value: 'Antarctica/McMurdo',
    label: 'UTC+12:00 New Zealand Time - McMurdo',
    searchText: 'Antarctica/McMurdo Antarctica/McMurdo New Zealand Time Antarctica AQ McMurdo',
    offsetMinutes: 720,
  ),
  TimezoneOption(
    value: 'Pacific/Funafuti',
    label: 'UTC+12:00 Tuvalu Time - Funafuti',
    searchText: 'Pacific/Funafuti Pacific/Funafuti Tuvalu Time Tuvalu TV Funafuti',
    offsetMinutes: 720,
  ),
  TimezoneOption(
    value: 'Pacific/Wake',
    label: 'UTC+12:00 Wake Island Time - Wake',
    searchText: 'Pacific/Wake Pacific/Wake Wake Island Time United States Minor Outlying Islands UM Wake',
    offsetMinutes: 720,
  ),
  TimezoneOption(
    value: 'Pacific/Wallis',
    label: 'UTC+12:00 Wallis & Futuna Time - Mata-Utu',
    searchText: 'Pacific/Wallis Pacific/Wallis Wallis & Futuna Time Wallis and Futuna WF Mata-Utu',
    offsetMinutes: 720,
  ),
  TimezoneOption(
    value: 'Pacific/Chatham',
    label: 'UTC+12:45 Chatham Time - Chatham',
    searchText: 'Pacific/Chatham Pacific/Chatham NZ-CHAT Chatham Time New Zealand NZ Chatham',
    offsetMinutes: 765,
  ),
  TimezoneOption(
    value: 'Pacific/Kanton',
    label: 'UTC+13:00 Phoenix Islands Time - Kanton',
    searchText: 'Pacific/Kanton Pacific/Kanton Pacific/Enderbury Phoenix Islands Time Kiribati KI Kanton',
    offsetMinutes: 780,
  ),
  TimezoneOption(
    value: 'Pacific/Apia',
    label: 'UTC+13:00 Samoa Time - Apia',
    searchText: 'Pacific/Apia Pacific/Apia Samoa Time Samoa WS Apia',
    offsetMinutes: 780,
  ),
  TimezoneOption(
    value: 'Pacific/Fakaofo',
    label: 'UTC+13:00 Tokelau Time - Fakaofo',
    searchText: 'Pacific/Fakaofo Pacific/Fakaofo Tokelau Time Tokelau TK Fakaofo',
    offsetMinutes: 780,
  ),
  TimezoneOption(
    value: 'Pacific/Tongatapu',
    label: 'UTC+13:00 Tonga Time - Nuku‘alofa',
    searchText: 'Pacific/Tongatapu Pacific/Tongatapu Tonga Time Tonga TO Nuku‘alofa',
    offsetMinutes: 780,
  ),
  TimezoneOption(
    value: 'Pacific/Kiritimati',
    label: 'UTC+14:00 Line Islands Time - Kiritimati',
    searchText: 'Pacific/Kiritimati Pacific/Kiritimati Line Islands Time Kiribati KI Kiritimati',
    offsetMinutes: 840,
  ),
];
